name: simple_3d
description: This package was created for the convenience of 3D non-experts, including scientists.
version: 16.1.1
repository: https://github.com/MasahideMori-SimpleAppli/simple_3d

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  file_state_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_lint: ^1.0.0